package com.bankasset.enums;

public enum AssetType {
    LAPTOP, DESKTOP, SERVER, MONITOR, PRINTER, SCANNER,
    PHONE, TABLET, ROUTER, SWITCH, UPS, ATM,
    POS_TERMINAL, CASH_COUNTER, SAFE, CAMERA,
    ACCESS_CONTROL, DESK, CHAIR, CABINET, OTHER
}
